apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app: postgres
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate  # Important for database deployments with persistent storage
  selector:
    matchLabels:
      app: postgres
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: postgres
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: postgres
          containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: {{ .Values.database.name }}
        - name: POSTGRES_USER
          value: {{ .Values.database.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.database.password }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        {{- if .Values.initScript.enabled }}
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        {{- end }}
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - {{ .Values.database.user }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - {{ .Values.database.user }}
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: postgres-data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-postgres-data
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- if .Values.initScript.enabled }}
      - name: init-script
        configMap:
          name: {{ .Release.Name }}-postgres-init
      {{- end }}