apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: backend
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: backend
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: backend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        # Main database connection string with secrets
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.existingSecret | default (printf "%s-backend-secrets" .Release.Name) }}
              key: DATABASE_URL
              optional: true
        # Alternative: Build connection string from individual environment variables
        - name: DB_HOST
          value: {{ .Release.Name }}-{{ .Values.database.host }}
        - name: DB_PORT
          value: "{{ .Values.database.port }}"
        - name: DB_NAME
          value: {{ .Values.database.name }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.existingSecret | default (printf "%s-backend-secrets" .Release.Name) }}
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.existingSecret | default (printf "%s-backend-secrets" .Release.Name) }}
              key: DB_PASSWORD
        # Load environment variables from ConfigMap
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-backend-config
              key: APP_ENV
        - name: APP_DEBUG
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-backend-config
              key: APP_DEBUG
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 12 }}