apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app: postgres
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres
    release: {{ .Release.Name }}
  type: ClusterIP