# Global values shared across all subchart
global:
  domain: chart-example.local
  environment: production

postgres:
  enabled: true
  image:
    repository: postgres
    tag: 15.3
    pullPolicy: IfNotPresent
  service:
    port: 5432
  persistence:
    enabled: true
    size: 1Gi
  database:
    name: app
    user: postgres
    password: postgres
  initScript:
    enabled: true

backend:
  enabled: true
  image:
    repository: backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 8000
    type: ClusterIP
  ingress:
    enabled: true
    className: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: "${global.domain}"
        paths:
          - path: /api
            pathType: Prefix
  database:
    host: postgres
    port: 5432
    name: app
    user: postgres
    password: postgres
    existingSecret: ""  # Set this to use an existing secret instead of creating one
  # Environment variables configuration
  env:
    environment: "${global.environment}"
    debug: "false"

frontend:
  enabled: true
  image:
    repository: frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 80
    type: ClusterIP
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: "${global.domain}"
        paths:
          - path: /
            pathType: Prefix
  api:
    url: /api