apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secrets
  labels:
    app: backend
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.database.existingSecret }}
  # Use existing secret for database credentials
  {{- else }}
  # Generate secrets from values
  DB_USER: {{ .Values.database.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-%s:%d/%s" .Values.database.user .Values.database.password .Release.Name .Values.database.host (.Values.database.port | int) .Values.database.name | b64enc | quote }}
  {{- end }}