apiVersion: v2
name: umbrella
description: A Helm chart for the complete user management application
version: 0.1.0
type: application
dependencies:
  - name: postgres
    version: 0.1.0
    repository: file://../postgres
    condition: postgres.enabled
  - name: backend
    version: 0.1.0
    repository: file://../backend
    condition: backend.enabled
  - name: frontend
    version: 0.1.0
    repository: file://../frontend
    condition: frontend.enabled
